on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            os: ubuntu-latest
          - java: 11
            os: macos-latest
          - java: 25
            os: ubuntu-latest
    steps:
    - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - shell: bash
      name: install sbt
      run: curl -Ls https://raw.githubusercontent.com/dwijnand/sbt-extras/103ab5905df0d7be505e258fc600935bbb511ec9/sbt > ./sbt && chmod 0755 ./sbt
    - uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8.1.1
    - run: ./sbt -v ";+check ;+cpl ;+test; +doc; lint"
