on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            os: ubuntu-latest
          - java: 11
            os: macos-latest
          - java: 25
            os: ubuntu-latest
    steps:
    - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - shell: bash
      name: install sbt
      run: curl -Ls https://raw.githubusercontent.com/dwijnand/sbt-extras/103ab5905df0d7be505e258fc600935bbb511ec9/sbt > ./sbt && chmod 0755 ./sbt
    - uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8.1.1
    - run: ./sbt -v ";+check ;+cpl ;+test; +doc; lint"
